# -*- coding: utf-8 -*-
"""olympic_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPrBf4LfZ4gvo1QZF-M2shOcNq1XA5Y1
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("athlete_events.csv.zip")

print(df.head())

medals = df.dropna(subset=["Medal"])

top10 = medals.groupby("Team")["Medal"].count().sort_values(ascending=False).head(10)

print(top10)

import matplotlib.pyplot as plt

plt.figure()
top10.plot(kind="bar")
plt.title("Top 10 Countries by Olympic Medals")
plt.xlabel("Country")
plt.ylabel("Total Medals")
plt.show()

yearly = medals.groupby("Year")["Medal"].count()

plt.figure()
yearly.plot()
plt.title("Total Olympic Medals Over Years")
plt.xlabel("Year")
plt.ylabel("Medals")
plt.show()

india = medals[medals["Team"] == "India"]

india_year = india.groupby("Year")["Medal"].count()

plt.figure()
india_year.plot()
plt.title("India Olympic Medal Trend")
plt.xlabel("Year")
plt.ylabel("Medals")
plt.show()

medal_dist = medals["Medal"].value_counts()

plt.figure()
plt.pie(medal_dist, labels=medal_dist.index, autopct='%1.1f%%')
plt.title("Medal Distribution")
plt.show()